name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: TypeScript Build
      # You may pin to the exact commit or the version.
      # uses: alexthemaster/action-build-typescript@d0935101a24426420d5bd5692a4cf16631cd6605
      uses: alexthemaster/action-build-typescript@v1.3.1
      with:
        # Whether or not to push the compiled code to a different branch
        pushToBranch: pg-build
        # The name of the branch the action should push the compiled code
        branch: dist

